
GET http://127.0.0.1:5000/carts HTTP/1.1

### 
POST http://127.0.0.1:5000/carts HTTP/1.1
Content-Type: application/json

{
    "name": "Teclado aaaa"
}

###

PATCH http://127.0.0.1:5000/carts/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Tecladinhos"
}

### 
DELETE http://127.0.0.1:5000/carts/2 HTTP/1.1
Content-Type: application/json

